pipeline {
    agent any
    stages{
        stage("Clean up"){
            steps {
                deleteDir()
            }
        }
        stage("Clone repo"){
            steps {
                sh "git clone git@github.com:Anand-Krishnan-M-J/Learning_Jenkins.git" 
            }
        }
        stage("Build"){
            steps{
                dir("Learning_Jenkins"){

                    sh "npm i"
                }
            }
        }
        stage("Test"){
            steps{
                dir("Learning_Jenkins"){

                    sh "npm run test"
                }
            }
        }
    }

}
